### ISSUE TITLE
"See what's installed": also see what's NOT installed

### ISSUE THREAD

**Issue by VioletGiraffe** [ME3Tweaks/MassEffectModManager#388]
It would be great to be able to see which mods have been added to the main list but not installed. Could you please implement that? That way I could see if I missed something, as my list of mods got quite large.

P. S. I want to take a moment to say that I'm not just pleased or surprised, I'm **SHOCKED** by how well the ME3TMM works and how sophisticated the modding framework is. Easy to use for us end users, hard to break the game or do something wrong. Thank you for your work!

**Comment by Mgamerz** [comment]
Due to how mods are installed, what is installed and what is in the library are two separate things, so this would not be a trivial task. It's the same reason that mods don't get marked as 'whats installed' in the mod library - because conditional install may mean some of a mod is installed or not. At some point I want to make it so the installation information panel can be split to a separate window, but that's a whole different ordeal. Your best workaround would be to just use Batch Installer.

**Comment by VioletGiraffe** [comment]
I think I understand why it's not immediately visible in the library (it has to account for the selected target, I can have two copies of LE2 with different sets of mods etc.). That's why "see what's installed" is a special separate tool and it refreshes/re-populates every time you invoke it. But the library seems to be just one entity, why can't the "What's installed" dialog query it and add entries that are present in the library and not found in the target game in any capacity?

**Comment by VioletGiraffe** [comment]
I think I see the problem, it shows installed DLC mods but not all mods are DLC mods. Oh well. Still, would be nice to see the list of known but not installed DLC mods, at least.
