### ISSUE TITLE
Feature Request: Batch Installer - Sort mods by Mount Priority

### ISSUE THREAD

**Issue by UtilityPawn** [ME3Tweaks/MassEffectModManager#399]
is it possible to have a sort button on mod manager/batch mod installer so we can for example sort by mount number so the highest mounted mods would be at the bottom list to make mod configurations easier? it only seems to be in alphabetical order by name default. it does get difficult remembering mount numbers the more mods downloaded especially when more patches/new mods keep coming out.

![Capture](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/154812945/24f1db45-eede-4890-8590-c41ed93987ac)

![Capture2](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/154812945/29a75391-2ff3-4701-9654-51a3b9a3b6e6)

**Comment by Mgamerz** [comment]
I've poked around with this the last few days and got a semi-working implementation. This is definitely not a cure all - mods that don't have DLC folders won't benefit from this. Internally, if a mod has multiple DLC folders it ALWAYS installs (alternates will not be factored into this), it takes the lowest, as typically the lowest will be the main one.

![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/2965370d-8c94-44c7-8573-d87479ebd908)

The UI here is ugly, as it was just a test. In this case I have it sorted backwards, something I'll fix. It may also be useful to show mount priorities here, but it's something I might put behind beta or dev mode because users should not be concerned with mount priority, unless they understand it.

**Comment by Mgamerz** [comment]
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/be0fa1f9-706e-4722-83bb-a5426fd70e5e)

Moved to the list of mods in the list, and now shows mount priority (best effort detection of it). It orders low to high since higher mods should patch lower ones.

**Comment by Mgamerz** [comment]
Moddesc needs a new descriptor to change sort order. Per the extended conversation at https://discord.com/channels/384874253448642570/1122216512615362672/1247888270373687388 one to do highest or lowest when detecting for batch installer would probably suffice.

**Comment by Mgamerz** [comment]
Implemented in 9.0
