### ISSUE TITLE
Display Install Status of the mod directly at main window inside "Mod Library"

### ISSUE THREAD

**Issue by ALIENQuake** [ME3Tweaks/MassEffectModManager#409]
Hi,

Can you add the Install Status of the mod indication directly at the main window inside "Mod Library"? A checkbox/green "plus" sign etc

Rationale: it's uncomfortable and tedious to constantly open 'Manage Target" and compare the content with the list of all available mods.

**Comment by Mgamerz** [comment]
This would only work for DLC mods. There has been work in previous builds that will help enable this feature (though it won't be fully reliable, due to how Mod Manager works internally since inception). This might be available in Mod Manager 9 as an experimental feature that can be turned on. I don't want a half-baked feature on by default.

**Comment by Mgamerz** [comment]
Implemented in 9.0, when in beta mode. It isn't going to ever be fully reliable so this will never make it out of Beta mode, I think.
